### ISSUE TITLE
add modpost and mod reply embeds

### ISSUE THREAD

**Issue by Hiviexd** [Hiviexd/axer-bot#56]
so when posting a modpost link, embed should show: 
- poster pfp + name
- artist-title of the map alongside a link 
- embed color would be the same as usergroup
- type of post (problem, suggestion, hype, praise, note, reply, reopen, resolve) along with a discord emote that matches color of each type of event)
- content of the post and truncates if it's too long.
- could maybe add a map banner at the bottom but idk

**Comment by Sebola3461** [comment]
done

**Comment by Sebola3461** [comment]
shit
