### ISSUE TITLE
Command "-choose" breaks if using 2 or more or's

### ISSUE THREAD

**Issue by Kapitar** [Hiviexd/axer-bot#59]
This can be fixed using another more loyal seperator like ;

**Comment by Kapitar** [comment]
![image](https://user-images.githubusercontent.com/52191611/159634541-a42055c4-c90e-4c56-b03d-9c56825b6236.jpeg)

**Comment by Hiviexd** [comment]
bot works as intended when command is used properly, don't really see a need to address this + already fixed a crash that used to happen because of this

**Comment by Hiviexd** [comment]
applied a fix, should be less prone to error now
