### ISSUE TITLE
Help command showing commands with "!" symbol, when bot uses a custom prefix

### ISSUE THREAD

**Issue by Kapitar** [Hiviexd/axer-bot#60]
![image](https://user-images.githubusercontent.com/52191611/159634965-fe2749ff-5873-4a62-b2c8-9218b3a0eb4a.jpeg)![image](https://user-images.githubusercontent.com/52191611/159634973-f592b01b-c3a9-415d-baf0-441b4bac249f.jpeg)

**Comment by Sebola3461** [comment]
patacas

**Comment by Sebola3461** [comment]
fixed
